// <auto-generated />
namespace e_Library.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddPreOrderReturns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPreOrderReturns));
        
        string IMigrationMetadata.Id
        {
            get { return "202111101533132_AddPreOrderReturns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
